spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  logging:
    level:
      org.springframework:
        orm:
          jpa:
            nodeValue: INFO
            JpaTransactionManager: DEBUG
        transaction:
          nodeValue: INFO
          interceptor: TRACE
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: shareit
    password: shareit