hibernate:
  show_sql: FALSE
  jdbc:
    time_zone: UTC
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
    ru:
      practicum:
        shareit: TRACE
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: shareit
    url: jdbc:postgresql://localhost:5432/shareit
    username: shareit
  jpa:
    show-sql: FALSE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always